### ISSUE TITLE
(PronounDB) not working

### ISSUE THREAD

**Issue by daoodi** [Strencher/BetterDiscordStuff#178]
it isnt working like it shows normally but i cant add or remove

i uninstalled 3 times and reinstalled 
i also turned off all my themes and plugins to see if it worked but nothing

**Comment by Zacam** [comment]
Assuming you've gone to the Pronoun DB site to set one for you, and connected it to your Discord ID; it should still show locally set Pronoun's as assigned; but I have noted that it currently only shows up in the conversation chat area, and it took some time when I initially 'set up' for it to start rendering.

It used to show up on Profile Popups/sidecards (but not full profile views) until some recent Discord update that took place; so hopefully that will return soon.

At present, I've also noted that the Right-Click context for "Pronoun DB" to add/edit has disappeared; unsure if that's due to Discord Updates or other plugin updates that have happened (Ala BDContextMenu and/or BDFDB; but it randomly disappears and a "Reload" has to happen to restore it (which can as noted by bug #169 come into conflict with BetterRoleColors) where toggling PronounDB causes those to break.

**Comment by HypedDomi** [comment]
Broken due the recent Discord Update. Please use #296
