### ISSUE TITLE
Question for someone who might have the answer

### ISSUE THREAD

**Issue by Zzeyy** [Strencher/BetterDiscordStuff#331]
Were the plugins abandoned?
There are too many issues opened and AFAIK no updates over a long period of time.

**Comment by HypedDomi** [comment]
Strencher just don't have time for BD Stuff atm

**Comment by Zzeyy** [comment]
It's been 5 months last time I checked. That's a one long out-of-time moment.

**Comment by HypedDomi** [comment]
Well he has work to do and is working on other more important projects

**Comment by Strencher** [comment]
Feel free to contribute, I'm open for PR's, just don't have time to fix shit at the moment because it takes a long time to create small patches inside discord since their new minification doesn't make it any better. I'm at the point right now where I have to prioritize my projects that I work on the in limited amount of time that I still have.

**Comment by Zzeyy** [comment]
I can code only in lua and the level of coding is nothing you could use anyway, so that's that.
