### ISSUE TITLE
[Bug]: Duplicate badge icon showing

### ISSUE THREAD

**Issue by Midao133** [Strencher/BetterDiscordStuff#424]
### Plugin

UnreadCountBadge

### Bug Description

![image](https://github.com/user-attachments/assets/944b0229-185a-42ff-9ac7-3b2f5c267752)
it get duplicated when moving to or from another channel, sometime appearing more than twice
it takes the place of the Ping badge, and make it look like there is as many ping as there is message in a channel
![image](https://github.com/user-attachments/assets/f88ad8c6-6cc1-4242-b7ad-fcc763cf075b)
by right clicking, then switching between 2 other channel after each right click the badge keep duplicating forever, only reset when clicking on the channel
![image](https://github.com/user-attachments/assets/6b414e4f-5587-4ec5-888e-840d73011ec4)
![image](https://github.com/user-attachments/assets/69383675-2c94-44fa-9b6d-eae9adaca9ed)
![image](https://github.com/user-attachments/assets/089a0d0d-f440-4edf-8f63-d96ecffbfad5)
![image](https://github.com/user-attachments/assets/48f02427-9d3f-4ee8-870d-0c921e2fa620)

### Confirmation

- [X] I am using the latest version of the plugin
- [X] This issue has not already been reported

**Comment by domi-btnr** [comment]
Sadly, I don't have the working Code anymore for this Plugin. Could you send me the Plugin File?

**Comment by domi-btnr** [comment]
I think I fixed the Issue. Since the Plugin isn't officially fixed yet, I'll give you a "Beta" Version. Unfortunately, I can't upload JS Files directly in the Issue. I uploaded the Plugin here: https://files.catbox.moe/ln6r93.js 
Copy the Content and replace the old one with the new one by clicking on the Pencil in the Plugin Settings

Please tell me if that worked

**Comment by Midao133** [comment]
I worked indeed, thank you
