### ISSUE TITLE
[Copier] Reaction emojis are bugged

### ISSUE THREAD

**Issue by Miiiik** [Strencher/BetterDiscordStuff#73]
When trying to add multiple reaction emotes to a single message, you usually hold shift in order to add multiple emotes at once. I do not know why, but with the supposed latest version (1.1.1), this is not possible. What happens is the following: the emote window scrolls up to the top and you cannot select any emotes.

**Comment by Strencher** [comment]
I can reproduce that bug, i'll look into when i have time.

**Comment by Miiiik** [comment]
Cool, thank you

**Comment by spokrr** [comment]
I've determined that this issue is related to the button that shows up on the right side of a message when you hover over it, as if you disable that option, reactions work properly again. Most likely because when you hold shift it opens a second menu on the message? 
@Miiiik if you disable the 
![image](https://user-images.githubusercontent.com/69011306/134827211-8e58cd1e-a1b1-4c3e-8389-47a06778cb93.png)
setting then it works properly again.

**Comment by Strencher** [comment]
This is fixed in https://github.com/Strencher/BetterDiscordStuff/commit/7a3d4ef04656e3cb8600ebf46a05072ea56659c6
