### ISSUE TITLE
[Bug] Status everywhere not displaying on some elements

### ISSUE THREAD

**Issue by BlueStarBRS** [Strencher/BetterDiscordStuff#74]
Which plugin/theme is this about?
Statuséverywhere plugin

Describe the Bug
status is not showing on my self and not on answer boxes on my self

To Reproduce
answer someone and you will see how this happening and this bug o self its just happens over and over after a time

Expected Behavior
i see my self online and thats the statuses dont load slow sometimes in chat

Screenshots
![image](https://user-images.githubusercontent.com/25110093/129251981-8e69d4c8-b448-4f26-9a7f-b8341e5fd7d1.png)

Discord Version
latest one

additional:
if you are afk (auto afk) and go back to online you are not seeing your self online so this is a bug too like the bug above.
![image](https://user-images.githubusercontent.com/25110093/129252067-140261dd-dac3-4654-b919-cfd41e1a4468.png)

after a time to this happpens idk how  i think its happanes if i change settings 
(error and no pbs anymore in the chat)
![image](https://user-images.githubusercontent.com/25110093/129252381-43e961e5-7108-4361-b81b-7b21da906901.png)

**Comment by Strencher** [comment]
Thanks for the report, it seems that some elements aren't updated properly. Switch channels/server should fix the first two errors. About the last screenshot, i don't know. I might be a conflict with another plugin but i can't reproduce that error. It usually means that an error occurred and the error boundary catched it instead of crashing your discord.

**Comment by Strencher** [comment]
No response after almost one month. Closing this for now.
